Traceback (most recent call last):
  File "../../run.py", line 6, in <module>
    model = RNNModel(configs[int(sys.argv[1])-1])
IndexError: list index out of range
